rvm:
  - 2.2.3
  - jruby-9.0.0.0
before_install:
  - travis_retry gem install bundler
  - bundle --version
install:
  - travis_retry bundle install
before_script:
  - travis_retry appraisal install
script:
  - appraisal rake test