rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
before_install:
  - travis_retry gem install bundler
  - bundle --version
install:
  - travis_retry bundle install
before_script:
  - travis_retry bundle exec rake appraisal:setup
script:
  - bundle exec rake appraisal test