rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
branches:
  only:
    - master
gemfile:
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
before_install:
  - gem install bundler
  - bundle --version
  - gem install bundler --version '>= 1.2.2'
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/rails40.gemfile
    - rvm: jruby-18mode
      gemfile: gemfiles/rails40.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails40.gemfile
before_script:
  - "bundle exec rake appraisal:install"
script:
  - "bundle exec rake appraisal test"
